export interface Manufacturer {
  id: number;
  companyName: string;
  country: string;
  address: string;
  phone: string;
  manufacturer: boolean;
  operator: boolean;
  engineering: boolean;
  mro: boolean;
  repairCenter: boolean;
  rotorRepair: boolean;
  owner: boolean;
  company: boolean;
  components: boolean;
  services: boolean;
  repairer: boolean;
  provider: boolean;
  customer: boolean;
}

export interface LowerAssembly {
  structureNumber: string;
  nomenclature: Nomenclature;
  structureLabel: string;
  quantity: number;
  nextLowerAssembly?: LowerAssembly[];
}
export interface NomenclatureType {
  id: number;
  name: string;
  nomenclature: Nomenclature;
  lowerAssembly?: LowerAssembly[];
}

export interface AircraftModel {
  id: number;
  aircraftTypeDesignation: string;
  type: string;
  model: string;
  variant: string;
  company: Manufacturer;
}

export interface Aircraft {
  id: number;
  model: AircraftModel;
  registration: string;
  ageingWindow: string;
  lastTechLog: string;
  officialRegistration: string;
  msn: string;
  active: boolean;
  etops: boolean;
  kardexFollowUp: boolean;
  blocked: boolean;
  interfaced: boolean;
  date: Date;
  introductionDate: Date;
  acceptanceDate: Date;
}

export interface Nomenclature {
  id: number;
  pn: string;
  partNumber: string;
  manufacturerCode: string;
  description: string;
  equipmentType: string;
  productType: string;
  classificationHazardouness: string;
  hazardousnessLevel: string;
  specialHandlingCondition: string;
  packagingClassification: string;
  defaultIngredientType: string;
  accountUnit: string;
  packagingUnit: string;
  nmnogo: string;
  depreciationType: string;
  administratorCompanyCode: string;
  customsPriceCode: string;
  atapartBelongs: string;
  typeJobPerformed: string;
  officialAuthority: string;
  certificateNumber: string;
  workDuringDisposal: string;
  workDuringOverhaul: string;
  workDuringInspection2: string;
  workDuringInspection: string;
  nonStandardAgeingCode1: string;
  nonStandardAgeingCode2: string;
  nonStandardAgeingCode3: string;
  masterPN: string;
  materialFamily: string;
  blacklistReason: string;
  usrmaj: string;
  levelInStructure: number;
  coefficientPackagingUnit: number;
  parteigWhtStated: number;
  heightSated: number;
  lengthStated: number;
  widthStated: number;
  provisioningCodeUsed: number;
  currentAssetCode: number;
  administratorStoreCode: number;
  basicPrice: number;
  unitSalePrice: number;
  customsUnitPrice: number;
  numberInventoryCards: number;
  partShelfTime: number;
  maxCalendarDeadline: number;
  overhaulCalendarDeadline: number;
  inspectionToCalendarDeadline: number;
  inspectionCalendarDeadline: number;
  dateHourCreation: Date;
  dateHourUpdate: Date;
  containsModel: boolean;
  nlacode: boolean;
  hazardousMaterial: boolean;
  specialTransportCondition: boolean;
  specialStorageCondition: boolean;
  specialDisposalCondition: boolean;
  etopsEquipment: boolean;
  reliabilityTracking: boolean;
  approval: boolean;
  calendarFollowUp: boolean;
  referenceBlackList: boolean;
}

export interface Serialization {
  id: number;
  sn: string;
  nomenclature: Nomenclature;
}

export interface Kardex {
  id: number;
  serialisable: Serialization;
  positionOnAircraft: string;
  kardexPositionDescription: string;
  fin: string;
  amm: string;
  aircraftZone: string;
  calendarFollowUpType: string;
  nonStandardAgeing1: string;
  tycod2: string;
  nonStandard3: string;
  codeJobPerformedDuringOverhaul: string;
  codeJobPerformedDuringInspection2: string;
  codeJobPerformedDuringI0nspection: string;
  checkCodeLifeLimit: string;
  checkCodeOverhaul: string;
  checkCodeInspection2: string;
  checkCodeInspection: string;
  kardexProtocolType: string;
  phasing: string;
  nextHigherAssembly: string;
  structureNumber: string;
  levelPositionAircraft: string;
  lowestLevelHierarchy: string;
  amendmentNumber: string;
  amendmentDate: string;
  versiNumber: string;
  versionDate: string;
  potentialOrigin: string;
  potentialOriginProgram: string;
  keyWords1: string;
  keyWords2: string;
  keyWords3: string;
  keyWords4: string;
  keyWords5: string;
  maintenanceLevelMandatory: string;
  potentialLimit: number;
  aircraftAgeingInHoursEquipment: number;
  aircraftAgeingInCyclesEquipment: number;
  aircraftNonStandardAgeing1Equipment: number;
  aircraftNonStandardAgeing2Equipment: number;
  aircraftNonStandardAgeing3Equipment: number;
  aircraftNonStandardAgeing4Equipment: number;
  aircraftNonStandardAgeing5Equipment: number;
  aircraftNonStandardAgeing6Equipment: number;
  aircraftNonStandardAgeing7Equipment: number;
  aircraftNonStandardAgeing8Equipment: number;
  aircraftNonStandardAgeing9Equipment: number;
  aircraftNonStandardAgeing10Equipment: number;
  aircraftNonStandardAgeing11Equipment: number;
  aircraftNonStandardAgeing12Equipment: number;
  aircraftNonStandardAgeing13Equipment: number;
  aircraftNonStandardAgeing14Equipment: number;
  aircraftNonStandardAgeing15Equipment: number;
  aircraftNonStandardAgeing16Equipment: number;
  aircraftNonStandardAgeing17Equipment: number;
  aircraftNonStandardAgeing18Equipment: number;
  aircraftNonStandardAgeing19Equipment: number;
  aircraftNonStandardAgeing20Equipment: number;
  hLifelimit: number;
  hOverhaul: number;
  hInspection2: number;
  hInspection: number;
  cLifelimit: number;
  cOverhaul: number;
  cInspection: number;
  cInspection2: number;
  lifelimit: number;
  overhaul: number;
  inspection: number;
  inspection2: number;
  nonStandard1LifeLimit: number;
  nonStandard1Overhaul: number;
  nonStandard1Inspection2: number;
  nonStandard1Inspection: number;
  nonStandard2LifeLimit: number;
  nonStandard2Overhaul: number;
  nonStandard2Inspection2: number;
  nonStandard2Inspection: number;
  nonStandard3LifeLimit: number;
  nonStandard3Overhaul: number;
  nonStandard3Inspection2: number;
  nonStandard3Inspection: number;
  followedInSection: boolean;
  followedInLogBook: boolean;
  etops: boolean;
  optionalPosition: boolean;
  overhaulThreshold: boolean;
  inspectThreshold: boolean;
  nextHigherAssembylCode: boolean;
  controlledPotential: boolean;
  deactivatedPosition: boolean;
}
